let lessons = [
	{
        id: 1,
        subject: "Math",
        location: "London",
        price : 400,
        image: "",
        availablespace: 5,
        
    },
    {
        id: 2,
        subject: "English",
        location: "Hendon",
        price : 350,
        image: "",
        availablespace: 5,
        
    },
    {
        id: 3,
        subject: "Art",
        location: "Camden",
        price : 450,
        image: "",
        availablespace: 5,  
    },
    {
        id: 4,
        subject: "Science",
        location: "Canning Town",
        price : 600,
        image: "",
        availablespace: 5,    
    },
    {
        id: 5,
        subject: "Science",
        location: "Westfield",
        price : 550,
        image: "",
        availablespace: 5,    
    },
    {
        id: 6,
        subject: "Music",
        location: "Stratford",
        price : 250,
        image: "",
        availablespace: 5,    
    },
    {
        id: 7,
        subject: "UI/UX",
        location: "Westfield",
        price : 450,
        image: "",
        availablespace: 5,   
    },
    {
        id: 8,
        subject: "Mobile Development",
        location: "Chelsea",
        price : 950,
        image: "",
        availablespace: 5, 
    },
    {
        id: 9,
        subject: "Backend Development",
        location: "Chelsea",
        price : 950,
        image: "",
        availablespace: 5,
    },
    {
        id: 10,
        subject: "Biology",
        location: "Old Traford",
        price : 450,
        image: "",
        availablespace: 5,      
    },
]